/* Generated by Together */

#ifndef CCSVMANAGER_H
#define CCSVMANAGER_H

#include <fstream>
#include <iostream>
#include <stdlib.h>
#include <sstream>


#include "CPersistentStorage.h"

extern const char* POIType_ar[];

class CCSVManager: public CPersistentStorage {

public:

	CCSVManager();
	~CCSVManager();
	void setMediaName(std::string name);
	bool writeData(const CWpDatabase& wpDB, const CPOIDataBase& poiDB);
	bool readData(CWpDatabase& wpDB, CPOIDataBase &poiDB,MergeMode_en mode);

private:
	bool readPOIData(CPOIDataBase& poiDB, MergeMode_en mode);
	bool readWaypointData(CWpDatabase& wpDB, MergeMode_en mode);
private:
	std::string m_WpFileName;
	std::string m_POIFileName;
};
#endif //CCSVMANAGER_H
