/* Generated by Together */

#include "CGPSSensor.h"


CWayPoint CGPSSensor::getCurrentPosition()
{
	double latitude, longitude;
	string name = "USER_CURRENT_LOCATION";
	/**
	 * Get the latitude and longitude from the user.
	 */
	do{
		cout << "Enter a valid latitude"<<endl;
		cin>> latitude;
	}while(latitude < -90 || latitude > 90);

	do{
		cout << "Enter a valid longitude"<<endl;
		cin >> longitude;
	}while(longitude < -180 || longitude > 180);
	/**
	 * create the CWaypoint object based on the user input.
	 */
	CWayPoint UserWayPoint(name,latitude,longitude);

	return UserWayPoint;
}


CGPSSensor::CGPSSensor()
{


}
