/* Generated by Together */

#ifndef CNAVIGATIONSYSTEM_H
#define CNAVIGATIONSYSTEM_H
#include "CGPSSensor.h"
#include "CRoute.h"
#include "CPOIDataBase.h"
#include "CPOI.h"
#include "CWpDatabase.h"

/**
 * The main class for Navigation that creates the database,
 *  defines a route with waypoints and POIs, and prints the 
 * complete route.
 */
class CNavigationSystem {
public:

    /**
     * The default constructor. 
     */
    CNavigationSystem();

    /**
     * This API will create the main database required for the Navigation. It triggers the creation of Route and printing of the complete route.
     * 
     * Arguments:
     * None.
     * 
     * Return:
     * None. 
     */
    void run();


private:

    /**
     * This API triggers the input for the current location to be taken from the user. It then prints the details of the next nearest POI and the distance between the POI and the user input coordinates.
     * 
     * 
     * Arguments:
     * None.
     * 
     * Return:
     * None. 
     */
    void printDistanceFrmCurRouteToNxtPOI();

    /**
     * The API prints the complete route conssiting of waypoints and the POIs.
     * 
     * Arguments:
     * None.
     * 
     * Return:
     * None. 
     */
    void printRoute();

    /**
     * The API adds the different waypints and POIs to the route.
     * 
     * 
     * Arguments:
     * None.
     * 
     * Return:
     * None. 
     */
    void enterRoute();
private:

    /**
     * The member that is responisble for getting the input co-ordinates from the user.
     * @link aggregationByValue
     * @supplierCardinality 0..*
     * @clientCardinality 1
     */
    CGPSSensor m_GPSSensor;

    /**
     * The member that is used to define the route for the navigation system
     * @link aggregationByValue
     * @clientCardinality 1
     * @supplierCardinality 1..*
     */

    CRoute m_Route;
    /**
     * The member that will be used to create the database of POIs.
     * @link aggregationByValue
     * @supplierCardinality 0..*
     * @clientCardinality 1
     */
    CPOIDataBase m_POIDB;

    /**
     * @link aggregationByValue
     * @clientCardinality 1..*
     * @supplierCardinality 0..* 
     */
    CWpDatabase m_WaypointDB;

    /** @link dependency */
    /*# CPOI lnkCPOI; */
};
#endif //CNAVIGATIONSYSTEM_H
