/* Generated by Together */

#ifndef CPERSISTENTSTORAGE_H
#define CPERSISTENTSTORAGE_H

#include"CWpDatabase.h"
#include"CPOIDataBase.h"

class CPersistentStorage {

public:
	CPersistentStorage() {}
	virtual ~CPersistentStorage() {}
	virtual void setMediaName(std::string name) = 0;
	virtual bool writeData(const CWpDatabase& wpDB, const CPOIDataBase& poiDB) = 0;
	typedef enum
	{
		Merge_e,
		Replace_e
	} MergeMode_en;

	virtual bool readData(CWpDatabase& wpDB, CPOIDataBase &poiDB,MergeMode_en mode) = 0;


};
#endif //CPERSISTENTSTORAGE_H
