/* Generated by Together */

#include "CPOIDataBase.h"


void CPOIDataBase::addPOI(CPOI const& poi)
{
	/**
	 * insert the POI to the database.
	 */
	m_POI.insert(std::pair<string,CPOI>(poi.getName(),poi));
}

CPOIDataBase::CPOIDataBase()
{
	m_POI.clear();
}


CPOI* CPOIDataBase::getPtrToPOI(string name)
{
	/**
	 * search through the database to find the required name of desitnation.
	 */
	bool matchFound = 0;
	map<string, CPOI>::iterator ii;
	ii = m_POI.find(name);
	/**
	 * if match found then return the address of the matched POI.
	 */
	if (ii != m_POI.end()){
		matchFound = 1;
	}


	return ((matchFound == 0)? NULL: &m_POI[name]);
}

 CPOIDataBase::POI_map CPOIDataBase::getPOIMap(void) const
{
	return m_POI;
}

CPOIDataBase::~CPOIDataBase()
{

}


void CPOIDataBase::print()
{
	for(POI_map::iterator it = m_POI.begin(); it != m_POI.end(); ++it)
	{
		//
		cout<<"poiDB -- print======================="<<endl;
		//it->second.print(DEGMMSS_FORMAT);
		cout<< it->second;
	}
}

void CPOIDataBase::clearPOIDatabase()
{
	m_POI.clear();
}
